
# Some Functions on Tensor Assignment 1 PyTorch Zero to GANs

An short introduction about PyTorch and about the chosen functions. 

*   Function 1 : torch.arange()
*   Function 2 : torch.cat()
*   Function 3 : torch.view()
*   Function 4 : torch.diag()
*   Function 5 : touch.cat()

In [0]:
# Import torch and other required modules
import torch

## Function 1 -torch.arange()

Returns a 1-D tensor of size end-start/step with values from the interval [start, end) taken with common difference step beginning from start.



In [3]:
# Example 1
torch.arange(start=0,end=10,step=3)

tensor([0, 3, 6, 9])

We create a tensor using arange function where we give start to be 0 and end to be 10 wit step 3 . So the first value will be zero and later i+3,



In [4]:
# Example 2
torch.arange(1,1.5,0.2)

tensor([1.0000, 1.2000, 1.4000])

We can also give it a float value and in return we get a list of tensors .



In [5]:
# Example 3 - breaking 
torch.arange([1,2,3])

TypeError: ignored

We cannot pass list when creating a tensor using arange , it only accepts start , end and step

Use this function when you need a specific tensors values

Closing comments about when to use this function

# Function 2 - torch.cat()
Concatenates the given sequence of seq tensors in the given dimension. 0-row 1-column

In [0]:
# Example 1 - working
x = torch.arange(1,10,3)
x
torch.cat((x,x,x),0)

First we create a tensor using arange function and then concatenate 3 times in rows



In [6]:
# Example 2 - working
new_data = torch.arange(1,24,2).reshape(-1,2)
new_data
torch.cat((new_data , torch.tensor([[1,2]])),0)

tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15],
        [17, 19],
        [21, 23],
        [ 1,  2]])

First we create a two dimensional arary and then concatenate them in rows



In [7]:
# Example 3 - breaking 
new_data
x
torch.cat((new_data,x))

NameError: ignored

When concatating tensor should have same dimesion , here when we tried to concat a tensor with (1,) dim with tensor with (2,) dim it thrown an error


*   Use this function when u want to make two tensor into one







Closing comments about when to use this function

## Function 3 - torch.view()
view() modifies the shape of the tensor. tensor.view returns a tensor that has the same data and same number of elements as the original tensor but changes only the shape of the tensor. view() does not change the underlaying data but only the shape.


In [8]:
# Example 1 - working 
a = torch.rand(3,5)
print(a.size())
b = a.view(15)
print(b.size())
c = a.view(-1,3)
print(c.size())

torch.Size([3, 5])
torch.Size([15])
torch.Size([5, 3])


b is a tensor created from a.view(15) that reshaped the 2D tensor into a 1D tensor. To create tensor c from a using tensor.view we passed the first dimension as -1 and second dimension as 3. The first dimension is inferred from the shape of original tensor.



In [9]:
# Example 2 - working
# Create tensor from NumPy array
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(a)
# Reshape to 3 dimensions: 3 rows, 1 cols, array of 2 items in last dimension
b = a.view(-1, 1, 2)
print(b, '\n', b.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[1, 2]],

        [[3, 4]],

        [[5, 6]]]) 
 torch.Size([3, 1, 2])


In this example, tensor a is reshaped from 2D to a 3D tensor using tensor.view



In [10]:
# Example 3 - breaking
a = torch.rand(3,5)
b = a.view(-1,2)

RuntimeError: ignored

The size of new tensor to be viewed should be compatible with the size of the original tensor. If not it throws an error. In this example, it is not possible to reshape the original tensor to have 2 columns as the number of elements in original tensor is not divisible by 2.

tensor.view is a very useful function while reshapeing a tensor.

## Function 4 - torch.diag(input, diagonal=0, out=None)

Used while dealing with the diagonal **elements**

In [11]:
# Example 1 - 
a = torch.randn(3)
a


tensor([-0.6226, -0.7727,  0.2172])

In [12]:
torch.diag(a)

tensor([[-0.6226,  0.0000,  0.0000],
        [ 0.0000, -0.7727,  0.0000],
        [ 0.0000,  0.0000,  0.2172]])

We can see the 1D array elements has been converted to 3D, where the array elments are converted into Diagonal Elements

In [13]:
# Example 2 - 
torch.diag(a, 1)

tensor([[ 0.0000, -0.6226,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.7727,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.2172],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])

We can see that by using 1 while defining the function we can set where to get the diagonal Elements.

In [14]:
# Example 3 - 
#Get the k-th diagonal of a given matrix:
a = torch.randn(3, 3)
a

tensor([[ 0.5209, -1.5485,  1.5142],
        [-0.0901, -0.3162,  1.8853],
        [-0.8377, -1.3644, -1.6201]])

In [15]:
torch.diag(a, 0)

tensor([ 0.5209, -0.3162, -1.6201])

In [16]:
torch.diag(a, 1)

tensor([-1.5485,  1.8853])

We can even get the Diagonal elements and also we can select which diagonal elemets we are going to select.

Diagonal functions heelp when we are required to deal with diagonal elements in a multi dimensional-tensor

## Function 5 - touch.cat()

Used to Concat two tensors



In [17]:
# Example 1

x = torch.tensor([[1,2,3],[4,5,6]] )
y = torch.tensor([[7,8,9],[10,11,12]])

torch.cat((x,y), 0)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

We can see that the the tensor are concatenated Verticaly


  * where 0- represents Dimension







In [18]:
# Example 2 
x = torch.tensor([[1,2,3],[4,5,6]] )
y = torch.tensor([[7,8,9],[10,11,12]])

torch.cat((x,y), 1)


tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])

We can see that the the tensor are concatenated Horizontaly
  * where 1- represents Dimension

In [19]:
# Example 3 - breaking 
# Example 3 - breaking (to illustrate when it breaks)
x = torch.tensor([[1,2,3],[4,5,6]] )
y = torch.tensor([[7,8,9],[10,11,12]])

torch.cat((x,y), 2)

IndexError: ignored

We can see that the two tensors are single dimension but the given dimension to contact is a higher dimension 
So their is an error.

Concat dunction can be used to join two tensor in the requ

## Conclusion

This notebooks covered some of the functions on tensors. For more infromation on these Functions and also many other functions are available at the documentation. link is given below.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...